version: '3.8'

services:
    svc-counter-app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: svc-counter-app
        dns:
            - 8.8.8.8
            - 8.8.4.4
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - otus_network
        depends_on:
            - svc-counter-redis
            - svc-counter-db
        environment:
            - QUEUE_CONNECTION=redis
        command: >
            sh -c "
            mkdir -p /var/www/storage /var/www/bootstrap/cache &&
            chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
            php-fpm
            "
        restart: unless-stopped

    svc-webserver:
        image: nginx:alpine
        container_name: svc-counter-webserver
        dns:
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - "8002:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - svc-counter-app
        networks:
            - otus_network
        restart: unless-stopped

    svc-counter-db:
        image: postgres:16
        container_name: svc-counter-db
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/postgresql/data
            - ./docker/postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
        command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
        ports:
            - "5435:5432"
        networks:
            - otus_network
        restart: unless-stopped

    svc-counter-redis:
        image: redis:alpine
        dns:
            - 8.8.8.8
            - 8.8.4.4
        container_name: svc-counter-redis
        ports:
            - "6382:6379"
        networks:
            - otus_network
        restart: unless-stopped

    svc-counter-worker:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: svc-counter-worker
        dns:
            - 8.8.8.8
            - 8.8.4.4
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - otus_network
        depends_on:
            - svc-counter-redis
            - svc-counter-db
        environment:
            - QUEUE_CONNECTION=redis
        command: >
            sh -c "
            php artisan queue:work --tries=1 --timeout=90
            "
        restart: unless-stopped

networks:
    otus_network:
        external: true

volumes:
    dbdata:
        driver: local
